---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - WEBUI_PORT=8080
    volumes:
      - /home/dacian/docker/qbittorrent/config:/config
      - /silver/mydata/starr/torrents:/starr/torrents
    ports:
      - 8180:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
