version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - /home/dacian/docker/heimdall:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    ports:
      - 6080:80
      - 6443:443
    restart: unless-stopped
