---
version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /home/dacian/docker/sabnzbd/:/config
      - /silver/mydata/starr/usenet:/starr/usenet #optional
    ports:
      - 8282:8080
    restart: unless-stopped
