version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANINTERVAL: 30m
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 12h
      ND_AUTOIMPORTPLAYLISTS: true
      ND_BASEURL: ""
    volumes:
      - "/home/dacian/docker/navidrome:/data"
      - "/silver/mydata/starr/media/music:/music:ro"


