version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 7080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dacian
      WORDPRESS_DB_PASSWORD: dedi
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: dacian
      MYSQL_PASSWORD: dedi
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
