version: "3.5"
services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    pid: host
    ports:
      - 61208:61208
    environment:
      - TZ=Australia/Melbourne
      - GLANCES_OPT=--webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf:/glances/conf
