---
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - MYSQL_ROOT_PASSWORD=deditom28
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=dacian
      - MYSQL_PASSWORD=deditom28
        #- REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - ./config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
