version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /home/dacian/docker/lidarr/config:/config
      - /silver/mydata/starr:/starr #optional
    ports:
      - 8686:8686
    restart: unless-stopped
