version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #"dacian"
      - PASS= #"dedi"
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /home/dacian/docker/transmission/config:/config
      - /silver/mydata/torrents:/downloads
      - /silver/mydata/torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
